services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
      - capital-gains
    restart: always

  stocks1-a:
    build:
      context: ./stockapi_updated
    container_name: stocks1-a
    ports:
      - "5001:8000"
    expose:
      - 8000
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/stocksdb
      - SPRING_PROFILES_ACTIVE=stocks1
    depends_on:
      - mongo
    restart: always

  stocks1-b:
    build:
      context: ./stockapi_updated
    container_name: stocks1-b
    expose:
      - 8000
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/stocksdb
      - SPRING_PROFILES_ACTIVE=stocks1
    depends_on:
      - mongo
    restart: always

  stocks2:
    build:
      context: ./stockapi_updated
    container_name: stocks2
    ports:
      - "5002:8000"
    expose:
      - 8000
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/stocksdb
      - SPRING_PROFILES_ACTIVE=stocks2
    depends_on:
      - mongo
    restart: always

  capital-gains:
    build:
      context: ./capitalgains
    container_name: capital-gains
    ports:
      - "5003:8080"
    environment:
      - stocks1.url=http://stocks1-a:8000
      - stocks2.url=http://stocks2:8000
    depends_on:
      - stocks1-a
      - stocks2
    restart: always

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
