apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080  # NodePort for the nginx service
        hostPort: 8080       # Changed from 80 to 8080 to avoid conflict
    extraMounts:
      - hostPath: /tmp/k8s-data  # Host machine path
        containerPath: /mnt/data  # Path inside the node container
    