apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-deployment
  namespace: stocks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
        - name: stocks
          image: stocks:latest
          ports:
            - containerPort: 8000
          env:
          - name: NINJA_API_KEY
            value: "GSBDSCF31HehCSxIozHtjw==CY8yGhcKCEU3ZNgG"  
          - name: MONGO_URI
            value: "mongodb://mongodb:27017/stocks"
          - name: mongo.collection
            value: "stocks"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /stocks
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /stocks
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always 
