apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: stocks
spec:
  selector:
    app: stocks
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
