apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: stocks
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb