apiVersion: v1
kind: Service
metadata:
  name: stocks
  namespace: stocks-app
spec:
  selector:
    app: stocks
  ports:
  - port: 8000        # Port the service listens on
    targetPort: 8000  # Port your application listens on
  type: ClusterIP     # Internal service type for load balancing
