apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: stocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: remove-default-conf
        image: busybox
        command: ['sh', '-c', 'rm -f /etc/nginx/conf.d/default.conf']
        volumeMounts:
        - name: nginx-conf-dir
          mountPath: /etc/nginx/conf.d
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-conf-dir
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-conf-dir
        emptyDir: {} 