apiVersion: v1
kind: Namespace
metadata:
  name: capitalgains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitalgains
  template:
    metadata:
      labels:
        app: capitalgains
    spec:
      containers:
        - name: capitalgains
          image: capitalgains:latest
          ports:
            - containerPort: 8080 
