apiVersion: v1
kind: Service
metadata:
  name: capitalgains-service
  namespace: capitalgains
spec:
  selector:
    app: capitalgains
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
